language: python

addons:
  postgresql: "9.4"
  firefox: "45.0"

services:
  - postgresql
  - redis-server

matrix:
    include:
        - python: 3.5
          env:
          - PYTHON_VERSION=python3.5
          - TOXENV=py35

# http://stackoverflow.com/a/19460794/315168
cache:
  directories:
    # /home/travis/.cache/pip/wheels is the normal pip cache folder
    - $HOME/.cache/pip
    - .tox

install:
  - travis_retry pip install tox

before_script:

  - pip install -U pip

# https://docs.travis-ci.com/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - psql -c 'create database blog_test;' -U postgres

# Downgrade Firefox until geckodriver + marionette matures
  - tar -xjf /tmp/firefox-45.0.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - echo "Using firefox version `firefox --version`"


script:
  # https://pypi.python.org/pypi/coverage_enable_subprocess
  - pip install coverage-enable-subprocess
  - export COVERAGE_PROCESS_START=$PWD/.coveragerc
  - export PATH=$PATH:$PWD/geth/
  - tox -- -x

after_success:
  # Update coverage information in codecov.io.
  - .tox/py35/bin/codecov
  # Dump package list so we have a log of last known good version set
  # This will simply fail under py34.
  - .tox/py35/bin/pip freeze

